<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-08 at 21:53:23.
 */
class steam_link_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var steam_link
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new steam_link;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers steam_link::get_type
     * @todo   Implement testGet_type().
     */
    public function testGet_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_link::get_link_object
     * @todo   Implement testGet_link_object().
     */
    public function testGet_link_object()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_link::get_source_object
     * @todo   Implement testGet_source_object().
     */
    public function testGet_source_object()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_link::set_link_object
     * @todo   Implement testSet_link_object().
     */
    public function testSet_link_object()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
