<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-08 at 21:53:23.
 */
class steam_calendar_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var steam_calendar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new steam_calendar;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers steam_calendar::get_type
     * @todo   Implement testGet_type().
     */
    public function testGet_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_calendar::get_last_monday
     * @todo   Implement testGet_last_monday().
     */
    public function testGet_last_monday()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_calendar::get_monday_first_calendar_week
     * @todo   Implement testGet_monday_first_calendar_week().
     */
    public function testGet_monday_first_calendar_week()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_calendar::get_monday_calendar_week
     * @todo   Implement testGet_monday_calendar_week().
     */
    public function testGet_monday_calendar_week()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_calendar::get_date_objects
     * @todo   Implement testGet_date_objects().
     */
    public function testGet_date_objects()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_calendar::get_entries
     * @todo   Implement testGet_entries().
     */
    public function testGet_entries()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_calendar::get_entries_calendar_week
     * @todo   Implement testGet_entries_calendar_week().
     */
    public function testGet_entries_calendar_week()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_calendar::check_conflicts
     * @todo   Implement testCheck_conflicts().
     */
    public function testCheck_conflicts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_calendar::get_calendar_data
     * @todo   Implement testGet_calendar_data().
     */
    public function testGet_calendar_data()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_calendar::add_entry_recursive
     * @todo   Implement testAdd_entry_recursive().
     */
    public function testAdd_entry_recursive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_calendar::add_entry
     * @todo   Implement testAdd_entry().
     */
    public function testAdd_entry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
