<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-08 at 21:53:23.
 */
class steam_group_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var steam_group
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new steam_group;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers steam_group::get_type
     * @todo   Implement testGet_type().
     */
    public function testGet_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::get_members
     * @todo   Implement testGet_members().
     */
    public function testGet_members()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::add_membership_request
     * @todo   Implement testAdd_membership_request().
     */
    public function testAdd_membership_request()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::get_membership_requests
     * @todo   Implement testGet_membership_requests().
     */
    public function testGet_membership_requests()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::requested_membership
     * @todo   Implement testRequested_membership().
     */
    public function testRequested_membership()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::remove_membership_request
     * @todo   Implement testRemove_membership_request().
     */
    public function testRemove_membership_request()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::invite_user
     * @todo   Implement testInvite_user().
     */
    public function testInvite_user()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::remove_invitation
     * @todo   Implement testRemove_invitation().
     */
    public function testRemove_invitation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::is_invited
     * @todo   Implement testIs_invited().
     */
    public function testIs_invited()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::get_invited
     * @todo   Implement testGet_invited().
     */
    public function testGet_invited()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::get_parent_and_group_name
     * @todo   Implement testGet_parent_and_group_name().
     */
    public function testGet_parent_and_group_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::check_group_pw
     * @todo   Implement testCheck_group_pw().
     */
    public function testCheck_group_pw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::add_member
     * @todo   Implement testAdd_member().
     */
    public function testAdd_member()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::add_members
     * @todo   Implement testAdd_members().
     */
    public function testAdd_members()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::remove_member
     * @todo   Implement testRemove_member().
     */
    public function testRemove_member()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::is_member
     * @todo   Implement testIs_member().
     */
    public function testIs_member()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::count_members
     * @todo   Implement testCount_members().
     */
    public function testCount_members()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::is_admin
     * @todo   Implement testIs_admin().
     */
    public function testIs_admin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::set_admin
     * @todo   Implement testSet_admin().
     */
    public function testSet_admin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::get_admins
     * @todo   Implement testGet_admins().
     */
    public function testGet_admins()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::set_password
     * @todo   Implement testSet_password().
     */
    public function testSet_password()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::has_password
     * @todo   Implement testHas_password().
     */
    public function testHas_password()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::get_parent_group
     * @todo   Implement testGet_parent_group().
     */
    public function testGet_parent_group()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::is_parent
     * @todo   Implement testIs_parent().
     */
    public function testIs_parent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::get_subgroups
     * @todo   Implement testGet_subgroups().
     */
    public function testGet_subgroups()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::create_subgroup
     * @todo   Implement testCreate_subgroup().
     */
    public function testCreate_subgroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::set_name
     * @todo   Implement testSet_name().
     */
    public function testSet_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::get_calendar
     * @todo   Implement testGet_calendar().
     */
    public function testGet_calendar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::get_workroom
     * @todo   Implement testGet_workroom().
     */
    public function testGet_workroom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::get_mails_filtered
     * @todo   Implement testGet_mails_filtered().
     */
    public function testGet_mails_filtered()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::mail
     * @todo   Implement testMail().
     */
    public function testMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::get_groupname
     * @todo   Implement testGet_groupname().
     */
    public function testGet_groupname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_group::drop_subGroupsLookupCache
     * @todo   Implement testDrop_subGroupsLookupCache().
     */
    public function testDrop_subGroupsLookupCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
