<?php

require dirname(dirname(__FILE__)) . '/etc/default.def.php';
require dirname(dirname(__FILE__)) . '/deps/vendor/autoload.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-08 at 21:53:23.
 */
class steam_document_Test extends PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new steam_document;
		$GLOBALS["STEAM"] = steam_connector::connect(STEAM_SERVER, STEAM_SERVER_PORT, STEAM_ROOT_LOGIN, STEAM_ROOT_PW);
		$this->assertTrue($GLOBALS["STEAM"]->get_login_status());
	}

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
		$GLOBALS["STEAM"]->disconnect();
	}

    /**
     * @covers steam_document::get_type
     * @todo   Implement testGet_type().
     */
    public function testGet_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::download
     * @todo   Implement testDownload().
     */
    public function testDownload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::get_reader
     * @todo   Implement testGet_reader().
     */
    public function testGet_reader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::is_read
     * @todo   Implement testIs_read().
     */
    public function testIs_read()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::set_content
     */
    public function testSet_content()
    {
		//creating object for testing
		$currentUser = $GLOBALS["STEAM"]->get_current_steam_user();
		$userHome = $currentUser->get_workroom();
		$testObject = steam_factory::create_document($GLOBALS["STEAM"]->get_id(), "Test Document.txt", "Hello World!", "text/plain", $userHome, "This is a document for testing.");

		$newContent = "Goodbye!";
		$testObject->set_content($newContent);
		$this->assertEquals($newContent, $testObject->get_content());

		//cleanup
		//$testObject->delete();
    }

    /**
     * @covers steam_document::get_content_size
     * @todo   Implement testGet_content_size().
     */
    public function testGet_content_size()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::get_content_id
     * @todo   Implement testGet_content_id().
     */
    public function testGet_content_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::get_content
     * @todo   Implement testGet_content().
     */
    public function testGet_content()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::delete_thumbnail
     * @todo   Implement testDelete_thumbnail().
     */
    public function testDelete_thumbnail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::delete_thumbnails
     * @todo   Implement testDelete_thumbnails().
     */
    public function testDelete_thumbnails()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::get_thumbnail
     * @todo   Implement testGet_thumbnail().
     */
    public function testGet_thumbnail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::get_thumbnail_data
     * @todo   Implement testGet_thumbnail_data().
     */
    public function testGet_thumbnail_data()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::get_content_html
     * @todo   Implement testGet_content_html().
     */
    public function testGet_content_html()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::get_version
     * @todo   Implement testGet_version().
     */
    public function testGet_version()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::get_previous_versions
     * @todo   Implement testGet_previous_versions().
     */
    public function testGet_previous_versions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_document::is_previous_version_of
     * @todo   Implement testIs_previous_version_of().
     */
    public function testIs_previous_version_of()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
