<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-08 at 21:53:24.
 */
class steam_object_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var steam_object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new steam_object;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers steam_object::get_type
     * @todo   Implement testGet_type().
     */
    public function testGet_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_id
     * @todo   Implement testGet_id().
     */
    public function testGet_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_object_class
     * @todo   Implement testGet_object_class().
     */
    public function testGet_object_class()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_all_attributes
     * @todo   Implement testGet_all_attributes().
     */
    public function testGet_all_attributes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_attributes
     * @todo   Implement testGet_attributes().
     */
    public function testGet_attributes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_cached_attributes
     * @todo   Implement testGet_cached_attributes().
     */
    public function testGet_cached_attributes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_attribute_cached
     * @todo   Implement testGet_attribute_cached().
     */
    public function testGet_attribute_cached()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_attribute
     * @todo   Implement testGet_attribute().
     */
    public function testGet_attribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_attribute_names
     * @todo   Implement testGet_attribute_names().
     */
    public function testGet_attribute_names()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_path
     * @todo   Implement testGet_path().
     */
    public function testGet_path()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_name
     * @todo   Implement testGet_name().
     */
    public function testGet_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_name
     * @todo   Implement testSet_name().
     */
    public function testSet_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_references
     * @todo   Implement testGet_references().
     */
    public function testGet_references()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_steam_connector
     * @todo   Implement testGet_steam_connector().
     */
    public function testGet_steam_connector()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::unlock_attribute
     * @todo   Implement testUnlock_attribute().
     */
    public function testUnlock_attribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::lock_attribute
     * @todo   Implement testLock_attribute().
     */
    public function testLock_attribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::is_locked
     * @todo   Implement testIs_locked().
     */
    public function testIs_locked()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_identifier
     * @todo   Implement testGet_identifier().
     */
    public function testGet_identifier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::unlock_attributes
     * @todo   Implement testUnlock_attributes().
     */
    public function testUnlock_attributes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_attribute
     * @todo   Implement testSet_attribute().
     */
    public function testSet_attribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::delete_attribute
     * @todo   Implement testDelete_attribute().
     */
    public function testDelete_attribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_attributes
     * @todo   Implement testSet_attributes().
     */
    public function testSet_attributes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_additional_values
     * @todo   Implement testSet_additional_values().
     */
    public function testSet_additional_values()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_additional_values
     * @todo   Implement testGet_additional_values().
     */
    public function testGet_additional_values()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_values
     * @todo   Implement testGet_values().
     */
    public function testGet_values()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_values
     * @todo   Implement testSet_values().
     */
    public function testSet_values()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_value
     * @todo   Implement testSet_value().
     */
    public function testSet_value()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::delete_value
     * @todo   Implement testDelete_value().
     */
    public function testDelete_value()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::steam_command
     * @todo   Implement testSteam_command().
     */
    public function testSteam_command()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_environment
     * @todo   Implement testGet_environment().
     */
    public function testGet_environment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_root_environment
     * @todo   Implement testGet_root_environment().
     */
    public function testGet_root_environment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_creator
     * @todo   Implement testGet_creator().
     */
    public function testGet_creator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_annotations
     * @todo   Implement testGet_annotations().
     */
    public function testGet_annotations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_annotations_filtered
     * @todo   Implement testGet_annotations_filtered().
     */
    public function testGet_annotations_filtered()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_annotating
     * @todo   Implement testGet_annotating().
     */
    public function testGet_annotating()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::remove_annotation
     * @todo   Implement testRemove_annotation().
     */
    public function testRemove_annotation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::add_annotation
     * @todo   Implement testAdd_annotation().
     */
    public function testAdd_annotation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::add_annotations
     * @todo   Implement testAdd_annotations().
     */
    public function testAdd_annotations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::move
     * @todo   Implement testMove().
     */
    public function testMove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::resolve_access
     * @todo   Implement testResolve_access().
     */
    public function testResolve_access()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_user_access
     * @todo   Implement testGet_user_access().
     */
    public function testGet_user_access()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_group_access
     * @todo   Implement testGet_group_access().
     */
    public function testGet_group_access()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::check_access
     * @todo   Implement testCheck_access().
     */
    public function testCheck_access()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_sanction
     * @todo   Implement testSet_sanction().
     */
    public function testSet_sanction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::sanction
     * @todo   Implement testSanction().
     */
    public function testSanction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::sanction_meta
     * @todo   Implement testSanction_meta().
     */
    public function testSanction_meta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_sanction
     * @todo   Implement testGet_sanction().
     */
    public function testGet_sanction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::query_sanction
     * @todo   Implement testQuery_sanction().
     */
    public function testQuery_sanction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_sanction_all
     * @todo   Implement testSet_sanction_all().
     */
    public function testSet_sanction_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::check_access_read
     * @todo   Implement testCheck_access_read().
     */
    public function testCheck_access_read()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::check_access_write
     * @todo   Implement testCheck_access_write().
     */
    public function testCheck_access_write()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::check_access_annotate
     * @todo   Implement testCheck_access_annotate().
     */
    public function testCheck_access_annotate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::check_access_insert
     * @todo   Implement testCheck_access_insert().
     */
    public function testCheck_access_insert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::check_access_move
     * @todo   Implement testCheck_access_move().
     */
    public function testCheck_access_move()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_read_access
     * @todo   Implement testSet_read_access().
     */
    public function testSet_read_access()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_annotate_access
     * @todo   Implement testSet_annotate_access().
     */
    public function testSet_annotate_access()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_rights_annotate
     * @todo   Implement testSet_rights_annotate().
     */
    public function testSet_rights_annotate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_insert_access
     * @todo   Implement testSet_insert_access().
     */
    public function testSet_insert_access()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_rights_insert
     * @todo   Implement testSet_rights_insert().
     */
    public function testSet_rights_insert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_write_access
     * @todo   Implement testSet_write_access().
     */
    public function testSet_write_access()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_acquire
     * @todo   Implement testSet_acquire().
     */
    public function testSet_acquire()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_acquire_from_environment
     * @todo   Implement testSet_acquire_from_environment().
     */
    public function testSet_acquire_from_environment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_acquire_attribute
     * @todo   Implement testSet_acquire_attribute().
     */
    public function testSet_acquire_attribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_acquire_attribute
     * @todo   Implement testGet_acquire_attribute().
     */
    public function testGet_acquire_attribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::get_acquire
     * @todo   Implement testGet_acquire().
     */
    public function testGet_acquire()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::describe_attributes
     * @todo   Implement testDescribe_attributes().
     */
    public function testDescribe_attributes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::is_prefetched
     * @todo   Implement testIs_prefetched().
     */
    public function testIs_prefetched()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_object::set_prefetched
     * @todo   Implement testSet_prefetched().
     */
    public function testSet_prefetched()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
