<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-08 at 21:53:23.
 */
class steam_exit_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var steam_exit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new steam_exit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers steam_exit::get_type
     * @todo   Implement testGet_type().
     */
    public function testGet_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_exit::get_exit
     * @todo   Implement testGet_exit().
     */
    public function testGet_exit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
