<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-08 at 21:53:24.
 */
class steam_user_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var steam_user
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new steam_user;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers steam_user::get_type
     * @todo   Implement testGet_type().
     */
    public function testGet_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::decline_contact_request
     * @todo   Implement testDecline_contact_request().
     */
    public function testDecline_contact_request()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::remove_contact
     * @todo   Implement testRemove_contact().
     */
    public function testRemove_contact()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::add_contact
     * @todo   Implement testAdd_contact().
     */
    public function testAdd_contact()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::add_unconfirmed_contact
     * @todo   Implement testAdd_unconfirmed_contact().
     */
    public function testAdd_unconfirmed_contact()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::add_confirmed_contact
     * @todo   Implement testAdd_confirmed_contact().
     */
    public function testAdd_confirmed_contact()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_full_name
     * @todo   Implement testGet_full_name().
     */
    public function testGet_full_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_workroom
     * @todo   Implement testGet_workroom().
     */
    public function testGet_workroom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_trashbin
     * @todo   Implement testGet_trashbin().
     */
    public function testGet_trashbin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_calendar
     * @todo   Implement testGet_calendar().
     */
    public function testGet_calendar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::rucksack_get_inventory
     * @todo   Implement testRucksack_get_inventory().
     */
    public function testRucksack_get_inventory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::rucksack_drop_objects
     * @todo   Implement testRucksack_drop_objects().
     */
    public function testRucksack_drop_objects()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::rucksack_set_current_folder
     * @todo   Implement testRucksack_set_current_folder().
     */
    public function testRucksack_set_current_folder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::rucksack_get_current_folder
     * @todo   Implement testRucksack_get_current_folder().
     */
    public function testRucksack_get_current_folder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::rucksack_get_subfolders
     * @todo   Implement testRucksack_get_subfolders().
     */
    public function testRucksack_get_subfolders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::rucksack_get_prior_folder
     * @todo   Implement testRucksack_get_prior_folder().
     */
    public function testRucksack_get_prior_folder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::rucksack_insert
     * @todo   Implement testRucksack_insert().
     */
    public function testRucksack_insert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_groups
     * @todo   Implement testGet_groups().
     */
    public function testGet_groups()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::set_password
     * @todo   Implement testSet_password().
     */
    public function testSet_password()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::check_password
     * @todo   Implement testCheck_password().
     */
    public function testCheck_password()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::activate
     * @todo   Implement testActivate().
     */
    public function testActivate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::is_activated
     * @todo   Implement testIs_activated().
     */
    public function testIs_activated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::enter
     * @todo   Implement testEnter().
     */
    public function testEnter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::set_email_forwarding
     * @todo   Implement testSet_email_forwarding().
     */
    public function testSet_email_forwarding()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::add_forward
     * @todo   Implement testAdd_forward().
     */
    public function testAdd_forward()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::delete_forward
     * @todo   Implement testDelete_forward().
     */
    public function testDelete_forward()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_email_forwarding
     * @todo   Implement testGet_email_forwarding().
     */
    public function testGet_email_forwarding()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::mail
     * @todo   Implement testMail().
     */
    public function testMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::send_email
     * @todo   Implement testSend_email().
     */
    public function testSend_email()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_mails
     * @todo   Implement testGet_mails().
     */
    public function testGet_mails()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_mails_filtered
     * @todo   Implement testGet_mails_filtered().
     */
    public function testGet_mails_filtered()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_sent_mail_folder
     * @todo   Implement testGet_sent_mail_folder().
     */
    public function testGet_sent_mail_folder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::create_sent_mail_folder
     * @todo   Implement testCreate_sent_mail_folder().
     */
    public function testCreate_sent_mail_folder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::set_sent_mail_folder
     * @todo   Implement testSet_sent_mail_folder().
     */
    public function testSet_sent_mail_folder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::is_storing_sent_mail
     * @todo   Implement testIs_storing_sent_mail().
     */
    public function testIs_storing_sent_mail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::set_is_storing_sent_mail
     * @todo   Implement testSet_is_storing_sent_mail().
     */
    public function testSet_is_storing_sent_mail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_ticket
     * @todo   Implement testGet_ticket().
     */
    public function testGet_ticket()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::set_buddies
     * @todo   Implement testSet_buddies().
     */
    public function testSet_buddies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_buddies
     * @todo   Implement testGet_buddies().
     */
    public function testGet_buddies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::is_buddy
     * @todo   Implement testIs_buddy().
     */
    public function testIs_buddy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::contact_confirm
     * @todo   Implement testContact_confirm().
     */
    public function testContact_confirm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::contact_is_confirmed
     * @todo   Implement testContact_is_confirmed().
     */
    public function testContact_is_confirmed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_confirmed_contacts
     * @todo   Implement testGet_confirmed_contacts().
     */
    public function testGet_confirmed_contacts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_unconfirmed_contacts
     * @todo   Implement testGet_unconfirmed_contacts().
     */
    public function testGet_unconfirmed_contacts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_user::get_status
     * @todo   Implement testGet_status().
     */
    public function testGet_status()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
