<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-08 at 22:28:23.
 */
class steam_connector_lite_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var steam_connector_lite
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new steam_connector_lite;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers steam_connector_lite::get_login_data
     * @todo   Implement testGet_login_data().
     */
    public function testGet_login_data()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connector_lite::get_root_room
     * @todo   Implement testGet_root_room().
     */
    public function testGet_root_room()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connector_lite::get_module
     * @todo   Implement testGet_module().
     */
    public function testGet_module()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connector_lite::get_factory
     * @todo   Implement testGet_factory().
     */
    public function testGet_factory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connector_lite::get_server_factory
     * @todo   Implement testGet_server_factory().
     */
    public function testGet_server_factory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connector_lite::list_server_modules
     * @todo   Implement testList_server_modules().
     */
    public function testList_server_modules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connector_lite::send_mail_from
     * @todo   Implement testSend_mail_from().
     */
    public function testSend_mail_from()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connector_lite::get_config_value
     * @todo   Implement testGet_config_value().
     */
    public function testGet_config_value()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
