<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-08 at 22:28:23.
 */
class steam_connection_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var steam_connection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new steam_connection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers steam_connection::get_instance
     * @todo   Implement testGet_instance().
     */
    public function testGet_instance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::set_socket_timeout
     * @todo   Implement testSet_socket_timeout().
     */
    public function testSet_socket_timeout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_socket_timeout
     * @todo   Implement testGet_socket_timeout().
     */
    public function testGet_socket_timeout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_id
     * @todo   Implement testGet_id().
     */
    public function testGet_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::read_socket
     * @todo   Implement testRead_socket().
     */
    public function testRead_socket()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::disconnect
     * @todo   Implement testDisconnect().
     */
    public function testDisconnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::is_connected
     * @todo   Implement testIs_connected().
     */
    public function testIs_connected()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_socket_status
     * @todo   Implement testGet_socket_status().
     */
    public function testGet_socket_status()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::reconnect
     * @todo   Implement testReconnect().
     */
    public function testReconnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::login
     * @todo   Implement testLogin().
     */
    public function testLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::command
     * @todo   Implement testCommand().
     */
    public function testCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::send_command
     * @todo   Implement testSend_command().
     */
    public function testSend_command()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::buffer_clear
     * @todo   Implement testBuffer_clear().
     */
    public function testBuffer_clear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::add_known_result
     * @todo   Implement testAdd_known_result().
     */
    public function testAdd_known_result()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::reset_known_results
     * @todo   Implement testReset_known_results().
     */
    public function testReset_known_results()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::buffer_flush
     * @todo   Implement testBuffer_flush().
     */
    public function testBuffer_flush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::buffer_attributes_request
     * @todo   Implement testBuffer_attributes_request().
     */
    public function testBuffer_attributes_request()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_transaction_id
     * @todo   Implement testGet_transaction_id().
     */
    public function testGet_transaction_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_module
     * @todo   Implement testGet_module().
     */
    public function testGet_module()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_factory
     * @todo   Implement testGet_factory().
     */
    public function testGet_factory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::predefined_command
     * @todo   Implement testPredefined_command().
     */
    public function testPredefined_command()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_version
     * @todo   Implement testGet_version().
     */
    public function testGet_version()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_current_steam_user
     * @todo   Implement testGet_current_steam_user().
     */
    public function testGet_current_steam_user()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_login_status
     * @todo   Implement testGet_login_status().
     */
    public function testGet_login_status()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_sentrequests
     * @todo   Implement testGet_sentrequests().
     */
    public function testGet_sentrequests()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_globalrequests
     * @todo   Implement testGet_globalrequests().
     */
    public function testGet_globalrequests()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_globalrequestsmap
     * @todo   Implement testGet_globalrequestsmap().
     */
    public function testGet_globalrequestsmap()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_globalrequestsTime
     * @todo   Implement testGet_globalrequestsTime().
     */
    public function testGet_globalrequestsTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_login_user_name
     * @todo   Implement testGet_login_user_name().
     */
    public function testGet_login_user_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::exception
     * @todo   Implement testException().
     */
    public function testException()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_login_data
     * @todo   Implement testGet_login_data().
     */
    public function testGet_login_data()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_server_version
     * @todo   Implement testGet_server_version().
     */
    public function testGet_server_version()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_config_value
     * @todo   Implement testGet_config_value().
     */
    public function testGet_config_value()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_steam_group
     * @todo   Implement testGet_steam_group().
     */
    public function testGet_steam_group()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::list_modules
     * @todo   Implement testList_modules().
     */
    public function testList_modules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_database
     * @todo   Implement testGet_database().
     */
    public function testGet_database()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_pike_version
     * @todo   Implement testGet_pike_version().
     */
    public function testGet_pike_version()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers steam_connection::get_last_reboot
     * @todo   Implement testGet_last_reboot().
     */
    public function testGet_last_reboot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
